spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        event-consumer:
          destination: data_stream
          contentType: application/json
        event-producer:
          destination: status_stream
          contentType: application/json
server:
  port: 8082

remote:
  storage:
    url: http://storage-service/api/v1/blob