apiVersion: v1
kind: Service
metadata:
  name: storage-service
  labels:
    app: storage-app
    name: storage-pod
spec:
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: storage-app
    name: storage-pod