version: '3.2'
services:
  kafdrop:
    image: obsidiandynamics/kafdrop:3.8.1
    container_name: kafdrop
    depends_on:
      - zookeeper
      - kafka
    expose:
      - 9000
    ports:
      - 9000:9000
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKERCONNECT: kafka:29092
    networks:
      - messaging-system-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - messaging-system-network
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - messaging-system-network

  ptc-storage:
    image: ptc-file-storage:latest
    restart: on-failure
    ports:
      - 8081:8081
    networks:
      - messaging-system-network  
  ptc-worker:
    image: ptc-worker:latest
    restart: on-failure
    depends_on:
      - kafdrop
    ports:
      - 8082:8082
    environment:
      SPRING_PROFILES_ACTIVE: local
    networks:
      - messaging-system-network
 
  ptc-processor:
    image: ptc-file-processor:latest
    restart: on-failure
    depends_on:
      - kafdrop
      - ptc-mysql
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: local
    networks:
      - messaging-system-network

  ptc-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fileDb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306
    networks:
      - messaging-system-network  

networks:
  messaging-system-network:      